<div class='row'>
	<div class='col-xs-1 col-md-1'></div>
	<div id='menu' class='col-xs-2 col-md-2'><?= "{$content['menu']}" ?></div>
	<div class='col-xs-8 col-md-8'>
		<div id='title' class='row'><?= "{$content['title']}" ?></div>
		<div id='content' class='row'><?= "{$content['content']}" ?></div>
	</div>
	<div class='col-xs-1 col-md-1'></div>
</div>
<div class='row'>
	<div class='col-xs-1 col-md-1'></div>
	<div id='footer' class='col-xs-10 col-md-10'>
		<?= "{$content['footer']}" ?>
	</div>
	<div class='col-xs-1 col-md-1'></div>
</div>
