<?php
	$bs_errors = [
		'success'	=>	'has_success',
		'warning'	=>	'has_warning',
		'error'		=>	'has_error'
	];
	$bs_glyph = [
		'success'	=>	'glyphicon-ok',
		'warning'	=>	'glyphicon-warning-sign',
		'error'		=>	'glyphicon-remove'
	];
?>

<form method='post'>
	<?php foreach ($items as $id => $param) : ?>
		<?php if ($id == 'submit') continue; ?>
		<div class='form-group has-feedback <?php if (isset($valid[$id])) echo $bs_errors[$valid[$id]] ?>'>
			<label for='<?= $id ?>' class='control-label'><?= $param['label'] ?>:</label>
			<?php if ($param['type'] != 'textarea') : ?>
				<input id='<?= $id ?>' name='<?= $id ?>' type='<?= $param['type'] ?>' class='form-control <?= $param['class'] ?>' style='<?= $param['style'] ?>'>
			<?php else : ?>
				<textarea id='<?= $id ?>' name='<?= $id ?>' class='<?= $param['class'] ?>' style='<?= $param['style'] ?>'></textarea>
			<?php endif; ?>
			<span class='glyphicon form-control-feedback <?php if (isset($valid[$id])) echo $bs_glyph[$valid[$id]] ?>'></span>
		</div>
	<?php endforeach; ?>
	<input type='hidden' name='csrf' value='<?= \Core\Session::getKey('csrf') ?>'/>
	<button id='submit' name='submit' value='submit' type='submit' class='btn btn-default'><?= (isset($items['submit'])) ? $items['submit'] : 'Submit' ?></button>
</form>
