<head>
	<meta charset='<?= $site->getCharset() ?>' />
	<title><?= $site->getTitle() ?></title>

	<?php if (($gtm_id = $site->getGtmId()) != '') : ?>
		<!-- Google Tag Manager -->
		<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
			new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
			j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
			'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
		})(window,document,'script','dataLayer','<?= $gtm_id ?>');</script>
		<!-- End Google Tag Manager -->
	<?php endif;?>

	<meta name='author' content='<?= $site->getAuthor() ?>'>
	<meta name='keywords' content='<?= $site->getKeywords() ?>'>
	<meta name='description' content='<?= $site->getDescription() ?>'>

	<meta name='viewport' content='width=device-width, initial-scale=1'>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
	<link rel="stylesheet" href='/public/css/default.css'>
</head>
