<head>
	<meta charset='<?= $site->getCharset() ?>' />
	<title><?= $site->getTitle() ?></title>
	<meta name='author' content='<?= $site->getAuthor() ?>'>
	<meta name='keywords' content='<?= $site->getKeywords() ?>'>
	<meta name='description' content='<?= $site->getDescription() ?>'>

	<meta name='viewport' content='width=device-width, initial-scale=1'>

	<link rel='stylesheet' href='/public/css/default.css' ?>
	<link rel="stylesheet" type="text/css" media="screen and (max-width: 323px)" href="/public/css/screen-max-323.css" />
	<link rel="stylesheet" type="text/css" media="screen and (max-width: 768px)" href="/public/css/screen-max-768.css" />
	<link rel="stylesheet" type="text/css" media="print" href="/public/css/print.css" />
</head>
